version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shareit-postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shareit -d shareit"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: